const data = [
  ["FAF", "isPartOf", "Air_System"],
  ["FAF", "hasPart", "FAF_Speed_Control"],
  ["FAF", "hasPart", "FAF_Running_Hour"],
  ["FAF", "hasPart", "FAF_On_Off_Control"],
  ["Room", "subClassOf", "Location"],
  ["Cooling_Tower", "isPartOf", "Water_System"],
  ["FCU_Running_Hour", "isPartOf", "FCU"],
  ["FCU", "isPartOf", "Air_System"],
  ["Energy_System", "hasPart", "EnergySys_WCC"],
  ["Energy_System", "hasPart", "EnergySys_AHU"],
  ["Energy_System", "subClassOf", "Electrical_System"],
  ["Electrical_System", "subClassOf", "System"],
  ["System", "subClassOf", "Class"],
  ["System", "type", "System"],
  ["EAF_On_Off_Control", "isPartOf", "EAF"],
  ["VAV_Zone_Air_Temperature_Setpoint", "isPartOf", "VAV"],
  ["FAF_On_Off_Control", "isPartOf", "FAF"],
  ["EnergySys_WCC", "isPartOf", "Energy_System"],
  ["Floor", "subClassOf", "Location"],
  ["FCU_Return_Air_Temperature", "isPartOf", "FCU"],
  ["FAF_Running_Hour", "isPartOf", "FAF"],
  ["EnergySys_AHU", "isPartOf", "Energy_System"],
  ["Condenser_Water_Pump", "isPartOf", "Water_System"],
  ["Air_System", "hasPart", "AHU"],
  ["Air_System", "hasPart", "PAU"],
  ["Air_System", "hasPart", "FAF"],
  ["Air_System", "hasPart", "FCU"],
  ["Air_System", "hasPart", "EAF"],
  ["Air_System", "hasPart", "VAV"],
  ["Air_System", "subClassOf", "HVAC_System"],
  ["HVAC_System", "subClassOf", "System"],
  ["PAU", "isPartOf", "Air_System"],
  ["AHU", "isPartOf", "Air_System"],
  ["AHU", "hasPart", "AHU_Supply_Air_Humidity"],
  ["AHU", "hasPart", "AHU_Return_Air_Damper_Control"],
  ["AHU", "hasPart", "AHU_Energy_Usage_Sensor"],
  ["AHU", "hasPart", "AHU_CO2_Concentration_Setpoint"],
  ["AHU", "hasPart", "AHU_Outdoor_Air_Temperature"],
  ["AHU", "hasPart", "AHU_Return_Air_Temperature_Setpoint"],
  ["AHU", "hasPart", "AHU_Outdoor_Air_Humidity"],
  ["AHU", "hasPart", "AHU_Supply_Air_Temperature"],
  ["AHU", "hasPart", "AHU_Outdoor_Air_CO2_Concentration"],
  ["AHU", "hasPart", "AHU_Return_Air_Temperature"],
  ["AHU", "hasPart", "AHU_Supply_Air_Flowrate"],
  ["AHU", "hasPart", "AHU_Return_Air_CO2_Concentration"],
  ["AHU", "hasPart", "AHU_Flow_Status"],
  ["AHU", "hasPart", "AHU_Water_Return_Temperature"],
  ["AHU", "hasPart", "AHU_Outdoor_Air_Flowrate"],
  ["AHU", "hasPart", "AHU_Supply_Air_Temperature_Setpoint"],
  ["AHU", "hasPart", "AHU_Return_Air_Humidity"],
  ["AHU", "hasPart", "AHU_Water_Supply_Temperature"],
  ["Water_System", "hasPart", "Chiller"],
  ["Water_System", "subClassOf", "HVAC_System"],
  ["Water_System", "hasPart", "Chilled_Water_Pump"],
  ["Water_System", "hasPart", "Cooling_Tower"],
  ["Water_System", "hasPart", "Condenser_Water_Pump"],
  ["PAU_Supply_Air_Humidity", "isPartOf", "PAU"],
  ["Fire_Safety_System", "subClassOf", "Safety_System"],
  ["Safety_System", "subClassOf", "System"],
  ["PAU_Shut_Off_Damper_Status", "isPartOf", "PAU"],
  ["VAV", "isPartOf", "Air_System"],
  ["VAV", "hasPart", "VAV_Damper_Position_Sensor"],
  ["VAV", "hasPart", "VAV_Zone_Air_Temperature_Sensor"],
  ["Building", "subClassOf", "Location"],
  ["Location", "subClassOf", "Class"],
  ["Location", "type", "Location"],
  ["EAF_Running_Hour", "isPartOf", "EAF"],
  ["EAF", "isPartOf", "Air_System"],
  ["EAF", "hasPart", "EAF_Speed_Control"],
  ["EAF", "hasPart", "EAF_Running_Hour"],
  ["EAF", "hasPart", "EAF_On_Off_Control"],
  ["Zone", "subClassOf", "Location"],
  ["Chilled_Water_Pump", "isPartOf", "Water_System"],
  ["EAF_Speed_Control", "isPartOf", "EAF"],
  ["FAF_Speed_Control", "isPartOf", "FAF"],
  ["35F", "subClassOf", "Floor"],
  ["27F", "subClassOf", "Floor"],
  ["36F", "subClassOf", "Floor"],
  ["28F", "subClassOf", "Floor"],
  ["29F", "subClassOf", "Floor"],
  ["03F", "subClassOf", "Floor"],
  ["30F", "subClassOf", "Floor"],
  ["31F", "subClassOf", "Floor"],
  ["32F", "subClassOf", "Floor"],
  ["33F", "subClassOf", "Floor"],
  ["34F", "subClassOf", "Floor"],
  ["07F", "subClassOf", "Floor"],
  ["08F", "subClassOf", "Floor"],
  ["10F", "subClassOf", "Floor"],
  ["09F", "subClassOf", "Floor"],
  ["11F", "subClassOf", "Floor"],
  ["12F", "subClassOf", "Floor"],
  ["13F", "subClassOf", "Floor"],
  ["14F", "subClassOf", "Floor"],
  ["15F", "subClassOf", "Floor"],
  ["16F", "subClassOf", "Floor"],
  ["17F", "subClassOf", "Floor"],
  ["19F", "subClassOf", "Floor"],
  ["20F", "subClassOf", "Floor"],
  ["21F", "subClassOf", "Floor"],
  ["22F", "subClassOf", "Floor"],
  ["23F", "subClassOf", "Floor"],
  ["26F", "subClassOf", "Floor"],
  ["37F", "subClassOf", "Floor"],
  ["38F", "subClassOf", "Floor"],
  ["39F", "subClassOf", "Floor"],
  ["40F", "subClassOf", "Floor"],
  ["41F", "subClassOf", "Floor"],
  ["42F", "subClassOf", "Floor"],
  ["43F", "subClassOf", "Floor"],
  ["44F", "subClassOf", "Floor"],
  ["45F", "subClassOf", "Floor"],
  ["46F", "subClassOf", "Floor"],
  ["18F", "subClassOf", "Floor"],
  ["47F", "subClassOf", "Floor"],
  ["05F", "subClassOf", "Floor"],
  ["06F", "subClassOf", "Floor"],
  ["25F", "subClassOf", "Floor"],
  ["B1F", "subClassOf", "Floor"],
  ["EnergySys_AHU", "isPartOf", "Energy_System"],
  ["EnergySys_WCC", "isPartOf", "Energy_System"],
  ["EAF", "isPartOf", "Air_System"],
  ["FAF", "isPartOf", "Air_System"],
  ["PAU", "isPartOf", "Air_System"],
  ["AHU", "isPartOf", "Air_System"],
  ["FCU", "isPartOf", "Air_System"],
  ["VAV", "isPartOf", "Air_System"],
  ["Chilled_Water_Pump", "isPartOf", "Water_System"],
  ["Cooling_Tower", "isPartOf", "Water_System"],
  ["Condenser_Water_Pump", "isPartOf", "Water_System"],
  ["Chiller", "isPartOf", "Water_System"],
  ["AHU-35-02", "isPointOf", "AHU"],
  ["AHU-07-01", "isPointOf", "AHU"],
  ["AHU-06-02", "isPointOf", "AHU"],
  ["AHU-06-01", "isPointOf", "AHU"],
  ["AHU-05-02", "isPointOf", "AHU"],
  ["AHU-05-01", "isPointOf", "AHU"],
  ["AHU-35-01", "isPointOf", "AHU"],
  ["AHU-41-01", "isPointOf", "AHU"],
  ["AHU-36-01", "isPointOf", "AHU"],
  ["AHU-28-01", "isPointOf", "AHU"],
  ["AHU-28-02", "isPointOf", "AHU"],
  ["AHU-27-02", "isPointOf", "AHU"],
  ["35F", "isLocationOf", "AHU-35-02"],
  ["35F", "isLocationOf", "AHU-35-01"],
  ["39F", "isLocationOf", "AHU-39-02"],
  ["40F", "isLocationOf", "AHU-40-02"],
  ["41F", "isLocationOf", "AHU-41-01"],
  ["AHU-27-02.Flow_Status.Status", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.S.A._Temperature.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.R.A._Humidity_1.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.R.A._Damper_Control.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.Water_Return_Temperature.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.O.A._Flowrate.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.O.A._Humidity.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.S.A._Flowrate.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.O.A._Temperature.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.R.A._Temperature_1.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.S.A._Humidity.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.R.A._CO2_Concentration.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.Water_Supply_Temperature.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.S.A._Temperature_Setpoint.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.CO2_Concentration_Setpoint.Value", "isPartOf", "AHU-27-02"],
  ["AHU-05-01.Flow_Status.Status", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.CO2_Concentration_Setpoint.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.S.A._Temperature_Setpoint.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.O.A._Humidity.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.Water_Supply_Temperature.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.R.A._CO2_Concentration.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.O.A._Temperature.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.Water_Return_Temperature.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.R.A._Humidity_1.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.O.A._Flowrate.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.R.A._Temperature_1.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.S.A._Humidity.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.S.A._Flowrate.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.S.A._Temperature.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.R.A._Damper_Control.Value", "isPartOf", "AHU-05-01"],
  ["AHU-27-02.Flow_Status.Status", "isPointOf", "AHU_Flow_Status"],
  [
    "AHU-27-02.S.A._Temperature.Value",
    "isPointOf",
    "AHU_Supply_Air_Temperature",
  ],
  ["AHU-27-02.R.A._Humidity_1.Value", "isPointOf", "AHU_Return_Air_Humidity"],
  [
    "AHU-27-02.R.A._Damper_Control.Value",
    "isPointOf",
    "AHU_Return_Air_Damper_Control",
  ],
  [
    "AHU-27-02.Water_Return_Temperature.Value",
    "isPointOf",
    "AHU_Water_Return_Temperature",
  ],
  ["AHU-27-02.O.A._Flowrate.Value", "isPointOf", "AHU_Outdoor_Air_Flowrate"],
  ["AHU-27-02.O.A._Humidity.Value", "isPointOf", "AHU_Outdoor_Air_Humidity"],
  ["AHU-27-02.S.A._Flowrate.Value", "isPointOf", "AHU_Supply_Air_Flowrate"],
  [
    "AHU-27-02.O.A._Temperature.Value",
    "isPointOf",
    "AHU_Outdoor_Air_Temperature",
  ],
  [
    "AHU-27-02.R.A._Temperature_1.Value",
    "isPointOf",
    "AHU_Return_Air_Temperature",
  ],
  ["AHU-27-02.S.A._Humidity.Value", "isPointOf", "AHU_Supply_Air_Humidity"],
  [
    "AHU-27-02.R.A._CO2_Concentration.Value",
    "isPointOf",
    "AHU_Return_Air_CO2_Concentration",
  ],
  [
    "AHU-27-02.Water_Supply_Temperature.Value",
    "isPointOf",
    "AHU_Water_Supply_Temperature",
  ],
  [
    "AHU-27-02.S.A._Temperature_Setpoint.Value",
    "isPointOf",
    "AHU_Supply_Air_Temperature_Setpoint",
  ],
  [
    "AHU-27-02.CO2_Concentration_Setpoint.Value",
    "isPointOf",
    "AHU_CO2_Concentration_Setpoint",
  ],
  ["FDD_AHU_CO2_Test", "isPartOf", "FDD_AHU"],
  ["FDD_AHU_S.A_SP_Temp_Test", "isPartOf", "FDD_AHU"],
  ["FDD_AHU_S.A_R.A_Temp_Test", "isPartOf", "FDD_AHU"],
  ["AHU", "hasFDD", "FDD_AHU"],
  ["Chiller_Contact_Sensor", "isPartOf", "Chiller"],
  ["Chiller_Supply_Chilled_Water_Temperature_Setpoint", "isPartOf", "Chiller"],
  ["Chiller_Return_Condenser_Water_Flow_Sensor", "isPartOf", "Chiller"],
  ["Chiller_On_Off_Status", "isPartOf", "Chiller"],
  ["Chiller_Temperature_Sensor", "isPartOf", "Chiller"],
  ["Chiller_Outside_Air_Temperature_Sensor", "isPartOf", "Chiller"],
  ["Chiller_Chilled_Water_Return_Temperature_Sensor", "isPartOf", "Chiller"],
  ["Chiller_Chilled_Water_Valve_On_Off_Control", "isPartOf", "Chiller"],
  ["Chiller_Chilled_Water_Supply_Temperature_Sensor", "isPartOf", "Chiller"],
  ["Chiller_CoP", "isPartOf", "Chiller"],
  ["Chiller_Outside_Air_Wet_Bulb_Temperature_Sensor", "isPartOf", "Chiller"],
  ["Chiller_Chilled_Water_Temperature_Reset", "isPartOf", "Chiller"],
  ["Chiller_Chilled_Water_Supply_Flow_Sensor", "isPartOf", "Chiller"],
  ["Chiller_CoP", "isPartOf", "Chiller"],
  ["Chiller_Cooling_Load", "isPartOf", "Chiller"],
  ["Chiller_Entering_Water_Temperature_Sensor", "isPartOf", "Chiller"],
  ["Chiller_Supply_Condenser_Water_Flow_Sensor", "isPartOf", "Chiller"],
  ["Chiller_Chilled_Water_Differential_Pressure_Sensor", "isPartOf", "Chiller"],
  ["Chiller_Return_Condenser_Water_Temperature_Sensor", "isPartOf", "Chiller"],
  ["Chilled_Chilled_Water_Pump_Delta_Temperature", "isPartOf", "Chiller"],
  [
    "Chiller_Supply_Condenser_Water_Temperature_Setpoint",
    "isPartOf",
    "Chiller",
  ],
  ["Chiller_Chilled_Water_Delta_Temperature", "isPartOf", "Chiller"],
  ["Chiller_Energy_Usage_Sensor", "isPartOf", "Chiller"],
  ["Chiller_Supply_Condenser_Water_Temperature_Sensor", "isPartOf", "Chiller"],
  ["Chiller_Cooling_Load", "subClassOf", "Virtual_Point"],
  ["CT_Approach_Temperature", "subClassOf", "Virtual_Point"],
  ["CT_Wet_Bulb", "subClassOf", "Virtual_Point"],
  [
    "Chilled_Chilled_Water_Pump_Delta_Temperature",
    "subClassOf",
    "Virtual_Point",
  ],
  ["Chiller_CoP", "subClassOf", "Virtual_Point"],
  ["AHU_Flow_Status", "isFDDPointOf", "FDD_AHU_S.A_SP_Temp_Test"],
  [
    "AHU_Supply_Air_Temperature_Setpoint",
    "isFDDPointOf",
    "FDD_AHU_S.A_SP_Temp_Test",
  ],
  ["AHU_Supply_Air_Temperature", "isFDDPointOf", "FDD_AHU_S.A_SP_Temp_Test"],
  ["B1F", "isLocationOf", "EnergySys_AHU"],
  ["B1F", "isLocationOf", "EnergySys_WCC"],
  ["WCC-25-03", "isPointOf", "Chiller"],
  ["25F", "isLocationOf", "WCC-25-03"],
  ["WCC-25-02", "isPointOf", "Chiller"],
  ["25F", "isLocationOf", "WCC-25-02"],
  ["WCC-25-01", "isPointOf", "Chiller"],
  ["25F", "isLocationOf", "WCC-25-01"],
  ["WCC-25-01.Chilled_Water_Temperature_Reset", "isPartOf", "WCC-25-01"],
  ["WCC-25-01.Chilled_Water_Return_Temperature.Value", "isPartOf", "WCC-25-01"],
  [
    "WCC-25-01.Condenser_Water_Differential_Pressure.Value",
    "isPartOf",
    "WCC-25-01",
  ],
  ["WCC-25-01.Condenser_Water_Valve_On_Off_Control", "isPartOf", "WCC-25-01"],
  [
    "WCC-25-01.Condenser_Water_Supply_Temperature.Value",
    "isPartOf",
    "WCC-25-01",
  ],
  ["WCC-25-01.Chilled_Water_Supply_Temperature.Value", "isPartOf", "WCC-25-01"],
  [
    "WCC-25-01.Chilled_Water_Differential_Pressure.Value",
    "isPartOf",
    "WCC-25-01",
  ],
  [
    "WCC-25-01.Condenser_Water_Return_Temperature.Value",
    "isPartOf",
    "WCC-25-01",
  ],
  ["WCC-25-01.Chilled_Water_Valve_On_Off_Control", "isPartOf", "WCC-25-01"],
  ["Points", 'subClassOf', 'Class'],
  ["Status", 'subClassOf', 'Points'],
  ["Sensor", 'subClassOf', 'Points'],
  ["Setpoint", 'subClassOf', 'Points'],
];

module.exports = data;
