const data = [
  ["FAF", "isPartOf", "Air_System"],
  ["FAF", "hasPart", "FAF_Speed_Control"],
  ["FAF", "hasPart", "FAF_Running_Hour"],
  ["FAF", "hasPart", "FAF_On_Off_Control"],
  ["Room", "subClassOf", "Location"],
  ["Cooling_Tower", "isPartOf", "Water_System"],
  ["FCU_Running_Hour", "isPartOf", "FCU"],
  ["FCU", "isPartOf", "Air_System"],
  ["Energy_System", "hasPart", "EnergySys_WCC"],
  ["Energy_System", "hasPart", "EnergySys_AHU"],
  ["Energy_System", "subClassOf", "Electrical_System"],
  ["Electrical_System", "subClassOf", "System"],
  ["System", "subClassOf", "Class"],
  ["System", "type", "System"],
  ["EAF_On_Off_Control", "isPartOf", "EAF"],
  ["VAV_Zone_Air_Temperature_Setpoint", "isPartOf", "VAV"],
  ["FAF_On_Off_Control", "isPartOf", "FAF"],
  ["EnergySys_WCC", "isPartOf", "Energy_System"],
  ["Floor", "subClassOf", "Location"],
  ["FCU_Return_Air_Temperature", "isPartOf", "FCU"],
  ["FAF_Running_Hour", "isPartOf", "FAF"],
  ["EnergySys_AHU", "isPartOf", "Energy_System"],
  ["Condenser_Water_Pump", "isPartOf", "Water_System"],
  ["Air_System", "hasPart", "AHU"],
  ["Air_System", "hasPart", "PAU"],
  ["Air_System", "hasPart", "FAF"],
  ["Air_System", "hasPart", "FCU"],
  ["Air_System", "hasPart", "EAF"],
  ["Air_System", "hasPart", "VAV"],
  ["Air_System", "subClassOf", "HVAC_System"],
  ["HVAC_System", "subClassOf", "System"],
  ["PAU", "isPartOf", "Air_System"],
  ["AHU", "isPartOf", "Air_System"],
  ["AHU", "hasPart", "AHU_Supply_Air_Humidity"],
  ["AHU", "hasPart", "AHU_Return_Air_Damper_Control"],
  ["AHU", "hasPart", "AHU_Energy_Usage_Sensor"],
  ["AHU", "hasPart", "AHU_CO2_Concentration_Setpoint"],
  ["AHU", "hasPart", "AHU_Outdoor_Air_Temperature"],
  ["AHU", "hasPart", "AHU_Return_Air_Temperature_Setpoint"],
  ["AHU", "hasPart", "AHU_Outdoor_Air_Humidity"],
  ["AHU", "hasPart", "AHU_Supply_Air_Temperature"],
  ["AHU", "hasPart", "AHU_Outdoor_Air_CO2_Concentration"],
  ["AHU", "hasPart", "AHU_Return_Air_Temperature"],
  ["AHU", "hasPart", "AHU_Supply_Air_Flowrate"],
  ["AHU", "hasPart", "AHU_Return_Air_CO2_Concentration"],
  ["AHU", "hasPart", "AHU_Flow_Status"],
  ["AHU", "hasPart", "AHU_Water_Return_Temperature"],
  ["AHU", "hasPart", "AHU_Outdoor_Air_Flowrate"],
  ["AHU", "hasPart", "AHU_Supply_Air_Temperature_Setpoint"],
  ["AHU", "hasPart", "AHU_Return_Air_Humidity"],
  ["AHU", "hasPart", "AHU_Water_Supply_Temperature"],
  ["Water_System", "hasPart", "Chiller"],
  ["Water_System", "subClassOf", "HVAC_System"],
  ["Water_System", "hasPart", "Chilled_Water_Pump"],
  ["Water_System", "hasPart", "Cooling_Tower"],
  ["Water_System", "hasPart", "Condenser_Water_Pump"],
  ["PAU_Supply_Air_Humidity", "isPartOf", "PAU"],
  ["Fire_Safety_System", "subClassOf", "Safety_System"],
  ["Safety_System", "subClassOf", "System"],
  ["PAU_Shut_Off_Damper_Status", "isPartOf", "PAU"],
  ["VAV", "isPartOf", "Air_System"],
  ["VAV", "hasPart", "VAV_Damper_Position_Sensor"],
  ["VAV", "hasPart", "VAV_Zone_Air_Temperature_Sensor"],
  ["Building", "subClassOf", "Location"],
  ["Location", "subClassOf", "Class"],
  ["Location", "type", "Location"],
  ["EAF_Running_Hour", "isPartOf", "EAF"],
  ["EAF", "isPartOf", "Air_System"],
  ["EAF", "hasPart", "EAF_Speed_Control"],
  ["EAF", "hasPart", "EAF_Running_Hour"],
  ["EAF", "hasPart", "EAF_On_Off_Control"],
  ["Zone", "subClassOf", "Location"],
  ["Chilled_Water_Pump", "isPartOf", "Water_System"],
  ["EAF_Speed_Control", "isPartOf", "EAF"],
  ["FAF_Speed_Control", "isPartOf", "FAF"],
  ["35F", "subClassOf", "Floor"],
  ["27F", "subClassOf", "Floor"],
  ["36F", "subClassOf", "Floor"],
  ["28F", "subClassOf", "Floor"],
  ["29F", "subClassOf", "Floor"],
  ["03F", "subClassOf", "Floor"],
  ["30F", "subClassOf", "Floor"],
  ["31F", "subClassOf", "Floor"],
  ["32F", "subClassOf", "Floor"],
  ["33F", "subClassOf", "Floor"],
  ["34F", "subClassOf", "Floor"],
  ["07F", "subClassOf", "Floor"],
  ["08F", "subClassOf", "Floor"],
  ["10F", "subClassOf", "Floor"],
  ["09F", "subClassOf", "Floor"],
  ["11F", "subClassOf", "Floor"],
  ["12F", "subClassOf", "Floor"],
  ["13F", "subClassOf", "Floor"],
  ["14F", "subClassOf", "Floor"],
  ["15F", "subClassOf", "Floor"],
  ["16F", "subClassOf", "Floor"],
  ["17F", "subClassOf", "Floor"],
  ["19F", "subClassOf", "Floor"],
  ["20F", "subClassOf", "Floor"],
  ["21F", "subClassOf", "Floor"],
  ["22F", "subClassOf", "Floor"],
  ["23F", "subClassOf", "Floor"],
  ["26F", "subClassOf", "Floor"],
  ["37F", "subClassOf", "Floor"],
  ["38F", "subClassOf", "Floor"],
  ["39F", "subClassOf", "Floor"],
  ["40F", "subClassOf", "Floor"],
  ["41F", "subClassOf", "Floor"],
  ["42F", "subClassOf", "Floor"],
  ["43F", "subClassOf", "Floor"],
  ["44F", "subClassOf", "Floor"],
  ["45F", "subClassOf", "Floor"],
  ["46F", "subClassOf", "Floor"],
  ["18F", "subClassOf", "Floor"],
  ["47F", "subClassOf", "Floor"],
  ["05F", "subClassOf", "Floor"],
  ["06F", "subClassOf", "Floor"],
  ["25F", "subClassOf", "Floor"],
  ["B1F", "subClassOf", "Floor"],
  ["EnergySys_AHU", "isPartOf", "Energy_System"],
  ["EnergySys_WCC", "isPartOf", "Energy_System"],
  ["EAF", "isPartOf", "Air_System"],
  ["FAF", "isPartOf", "Air_System"],
  ["PAU", "isPartOf", "Air_System"],
  ["AHU", "isPartOf", "Air_System"],
  ["FCU", "isPartOf", "Air_System"],
  ["VAV", "isPartOf", "Air_System"],
  ["Chilled_Water_Pump", "isPartOf", "Water_System"],
  ["Cooling_Tower", "isPartOf", "Water_System"],
  ["Condenser_Water_Pump", "isPartOf", "Water_System"],
  ["Chiller", "isPartOf", "Water_System"],
  ["AHU-35-02", "isPointOf", "AHU"],
  ["AHU-07-01", "isPointOf", "AHU"],
  ["AHU-06-02", "isPointOf", "AHU"],
  ["AHU-06-01", "isPointOf", "AHU"],
  ["AHU-05-02", "isPointOf", "AHU"],
  ["AHU-05-01", "isPointOf", "AHU"],
  ["AHU-47-01", "isPointOf", "AHU"],
  ["AHU-47-02", "isPointOf", "AHU"],
  ["AHU-18-01", "isPointOf", "AHU"],
  ["AHU-18-02", "isPointOf", "AHU"],
  ["AHU-46-02", "isPointOf", "AHU"],
  ["AHU-46-01", "isPointOf", "AHU"],
  ["AHU-45-02", "isPointOf", "AHU"],
  ["AHU-45-01", "isPointOf", "AHU"],
  ["AHU-44-02", "isPointOf", "AHU"],
  ["AHU-44-01", "isPointOf", "AHU"],
  ["AHU-43-02", "isPointOf", "AHU"],
  ["AHU-43-01", "isPointOf", "AHU"],
  ["AHU-42-02", "isPointOf", "AHU"],
  ["AHU-42-01", "isPointOf", "AHU"],
  ["AHU-41-02", "isPointOf", "AHU"],
  ["AHU-41-01", "isPointOf", "AHU"],
  ["AHU-40-02", "isPointOf", "AHU"],
  ["AHU-39-02", "isPointOf", "AHU"],
  ["AHU-40-01", "isPointOf", "AHU"],
  ["AHU-39-01", "isPointOf", "AHU"],
  ["AHU-38-02", "isPointOf", "AHU"],
  ["AHU-03-02", "isPointOf", "AHU"],
  ["AHU-38-01", "isPointOf", "AHU"],
  ["AHU-37-02", "isPointOf", "AHU"],
  ["AHU-36-02", "isPointOf", "AHU"],
  ["AHU-37-01", "isPointOf", "AHU"],
  ["AHU-26-02", "isPointOf", "AHU"],
  ["AHU-26-01", "isPointOf", "AHU"],
  ["AHU-23-01", "isPointOf", "AHU"],
  ["AHU-23-02", "isPointOf", "AHU"],
  ["AHU-22-02", "isPointOf", "AHU"],
  ["AHU-22-01", "isPointOf", "AHU"],
  ["AHU-21-02", "isPointOf", "AHU"],
  ["AHU-21-01", "isPointOf", "AHU"],
  ["AHU-20-02", "isPointOf", "AHU"],
  ["AHU-20-01", "isPointOf", "AHU"],
  ["AHU-19-01", "isPointOf", "AHU"],
  ["AHU-19-02", "isPointOf", "AHU"],
  ["AHU-17-02", "isPointOf", "AHU"],
  ["AHU-17-01", "isPointOf", "AHU"],
  ["AHU-16-02", "isPointOf", "AHU"],
  ["AHU-16-01", "isPointOf", "AHU"],
  ["AHU-15-02", "isPointOf", "AHU"],
  ["AHU-15-01", "isPointOf", "AHU"],
  ["AHU-14-02", "isPointOf", "AHU"],
  ["AHU-14-01", "isPointOf", "AHU"],
  ["AHU-13-02", "isPointOf", "AHU"],
  ["AHU-13-01", "isPointOf", "AHU"],
  ["AHU-12-02", "isPointOf", "AHU"],
  ["AHU-12-01", "isPointOf", "AHU"],
  ["AHU-11-02", "isPointOf", "AHU"],
  ["AHU-11-01", "isPointOf", "AHU"],
  ["AHU-09-02", "isPointOf", "AHU"],
  ["AHU-09-01", "isPointOf", "AHU"],
  ["AHU-10-02", "isPointOf", "AHU"],
  ["AHU-10-01", "isPointOf", "AHU"],
  ["AHU-08-02", "isPointOf", "AHU"],
  ["AHU-08-01", "isPointOf", "AHU"],
  ["AHU-07-02", "isPointOf", "AHU"],
  ["AHU-34-01", "isPointOf", "AHU"],
  ["AHU-34-02", "isPointOf", "AHU"],
  ["AHU-33-02", "isPointOf", "AHU"],
  ["AHU-33-01", "isPointOf", "AHU"],
  ["AHU-32-02", "isPointOf", "AHU"],
  ["AHU-32-01", "isPointOf", "AHU"],
  ["AHU-31-01", "isPointOf", "AHU"],
  ["AHU-31-02", "isPointOf", "AHU"],
  ["AHU-30-02", "isPointOf", "AHU"],
  ["AHU-30-01", "isPointOf", "AHU"],
  ["AHU-03-01", "isPointOf", "AHU"],
  ["AHU-29-02", "isPointOf", "AHU"],
  ["AHU-29-01", "isPointOf", "AHU"],
  ["AHU-27-01", "isPointOf", "AHU"],
  ["AHU-35-01", "isPointOf", "AHU"],
  ["AHU-36-01", "isPointOf", "AHU"],
  ["AHU-28-01", "isPointOf", "AHU"],
  ["AHU-28-02", "isPointOf", "AHU"],
  ["AHU-27-02", "isPointOf", "AHU"],
  ["35F", "isLocationOf", "AHU-35-02"],
  ["35F", "isLocationOf", "AHU-35-01"],
  ["36F", "isLocationOf", "AHU-36-01"],
  ["28F", "isLocationOf", "AHU-28-01"],
  ["28F", "isLocationOf", "AHU-28-02"],
  ["27F", "isLocationOf", "AHU-27-02"],
  ["27F", "isLocationOf", "AHU-27-01"],
  ["29F", "isLocationOf", "AHU-29-01"],
  ["29F", "isLocationOf", "AHU-29-02"],
  ["03F", "isLocationOf", "AHU-03-01"],
  ["30F", "isLocationOf", "AHU-30-01"],
  ["30F", "isLocationOf", "AHU-30-02"],
  ["31F", "isLocationOf", "AHU-31-02"],
  ["31F", "isLocationOf", "AHU-31-01"],
  ["32F", "isLocationOf", "AHU-32-01"],
  ["32F", "isLocationOf", "AHU-32-02"],
  ["33F", "isLocationOf", "AHU-33-01"],
  ["33F", "isLocationOf", "AHU-33-02"],
  ["34F", "isLocationOf", "AHU-34-02"],
  ["34F", "isLocationOf", "AHU-34-01"],
  ["07F", "isLocationOf", "AHU-07-02"],
  ["08F", "isLocationOf", "AHU-08-01"],
  ["08F", "isLocationOf", "AHU-08-02"],
  ["10F", "isLocationOf", "AHU-10-01"],
  ["10F", "isLocationOf", "AHU-10-02"],
  ["09F", "isLocationOf", "AHU-09-01"],
  ["09F", "isLocationOf", "AHU-09-02"],
  ["11F", "isLocationOf", "AHU-11-01"],
  ["11F", "isLocationOf", "AHU-11-02"],
  ["12F", "isLocationOf", "AHU-12-01"],
  ["12F", "isLocationOf", "AHU-12-02"],
  ["13F", "isLocationOf", "AHU-13-01"],
  ["13F", "isLocationOf", "AHU-13-02"],
  ["14F", "isLocationOf", "AHU-14-01"],
  ["14F", "isLocationOf", "AHU-14-02"],
  ["15F", "isLocationOf", "AHU-15-01"],
  ["15F", "isLocationOf", "AHU-15-02"],
  ["16F", "isLocationOf", "AHU-16-01"],
  ["16F", "isLocationOf", "AHU-16-02"],
  ["17F", "isLocationOf", "AHU-17-01"],
  ["17F", "isLocationOf", "AHU-17-02"],
  ["19F", "isLocationOf", "AHU-19-02"],
  ["19F", "isLocationOf", "AHU-19-01"],
  ["20F", "isLocationOf", "AHU-20-01"],
  ["20F", "isLocationOf", "AHU-20-02"],
  ["21F", "isLocationOf", "AHU-21-01"],
  ["21F", "isLocationOf", "AHU-21-02"],
  ["22F", "isLocationOf", "AHU-22-01"],
  ["22F", "isLocationOf", "AHU-22-02"],
  ["23F", "isLocationOf", "AHU-23-02"],
  ["23F", "isLocationOf", "AHU-23-01"],
  ["26F", "isLocationOf", "AHU-26-01"],
  ["26F", "isLocationOf", "AHU-26-02"],
  ["37F", "isLocationOf", "AHU-37-01"],
  ["36F", "isLocationOf", "AHU-36-02"],
  ["37F", "isLocationOf", "AHU-37-02"],
  ["38F", "isLocationOf", "AHU-38-01"],
  ["03F", "isLocationOf", "AHU-03-02"],
  ["38F", "isLocationOf", "AHU-38-02"],
  ["39F", "isLocationOf", "AHU-39-01"],
  ["40F", "isLocationOf", "AHU-40-01"],
  ["39F", "isLocationOf", "AHU-39-02"],
  ["40F", "isLocationOf", "AHU-40-02"],
  ["41F", "isLocationOf", "AHU-41-01"],
  ["41F", "isLocationOf", "AHU-41-02"],
  ["42F", "isLocationOf", "AHU-42-01"],
  ["42F", "isLocationOf", "AHU-42-02"],
  ["43F", "isLocationOf", "AHU-43-01"],
  ["43F", "isLocationOf", "AHU-43-02"],
  ["44F", "isLocationOf", "AHU-44-01"],
  ["44F", "isLocationOf", "AHU-44-02"],
  ["45F", "isLocationOf", "AHU-45-01"],
  ["45F", "isLocationOf", "AHU-45-02"],
  ["46F", "isLocationOf", "AHU-46-01"],
  ["46F", "isLocationOf", "AHU-46-02"],
  ["18F", "isLocationOf", "AHU-18-02"],
  ["18F", "isLocationOf", "AHU-18-01"],
  ["47F", "isLocationOf", "AHU-47-02"],
  ["47F", "isLocationOf", "AHU-47-01"],
  ["05F", "isLocationOf", "AHU-05-01"],
  ["05F", "isLocationOf", "AHU-05-02"],
  ["06F", "isLocationOf", "AHU-06-01"],
  ["06F", "isLocationOf", "AHU-06-02"],
  ["07F", "isLocationOf", "AHU-07-01"],
  ["AHU-27-02.Flow_Status.Status", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.S.A._Temperature.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.R.A._Humidity_1.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.R.A._Damper_Control.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.Water_Return_Temperature.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.O.A._Flowrate.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.O.A._Humidity.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.S.A._Flowrate.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.O.A._Temperature.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.R.A._Temperature_1.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.S.A._Humidity.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.R.A._CO2_Concentration.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.Water_Supply_Temperature.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.S.A._Temperature_Setpoint.Value", "isPartOf", "AHU-27-02"],
  ["AHU-27-02.CO2_Concentration_Setpoint.Value", "isPartOf", "AHU-27-02"],
  ["AHU-05-01.Flow_Status.Status", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.CO2_Concentration_Setpoint.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.S.A._Temperature_Setpoint.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.O.A._Humidity.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.Water_Supply_Temperature.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.R.A._CO2_Concentration.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.O.A._Temperature.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.Water_Return_Temperature.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.R.A._Humidity_1.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.O.A._Flowrate.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.R.A._Temperature_1.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.S.A._Humidity.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.S.A._Flowrate.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.S.A._Temperature.Value", "isPartOf", "AHU-05-01"],
  ["AHU-05-01.R.A._Damper_Control.Value", "isPartOf", "AHU-05-01"],
  ["AHU-27-02.Flow_Status.Status", "isPointOf", "AHU_Flow_Status"],
  [
    "AHU-27-02.S.A._Temperature.Value",
    "isPointOf",
    "AHU_Supply_Air_Temperature",
  ],
  ["AHU-27-02.R.A._Humidity_1.Value", "isPointOf", "AHU_Return_Air_Humidity"],
  [
    "AHU-27-02.R.A._Damper_Control.Value",
    "isPointOf",
    "AHU_Return_Air_Damper_Control",
  ],
  [
    "AHU-27-02.Water_Return_Temperature.Value",
    "isPointOf",
    "AHU_Water_Return_Temperature",
  ],
  ["AHU-27-02.O.A._Flowrate.Value", "isPointOf", "AHU_Outdoor_Air_Flowrate"],
  ["AHU-27-02.O.A._Humidity.Value", "isPointOf", "AHU_Outdoor_Air_Humidity"],
  ["AHU-27-02.S.A._Flowrate.Value", "isPointOf", "AHU_Supply_Air_Flowrate"],
  [
    "AHU-27-02.O.A._Temperature.Value",
    "isPointOf",
    "AHU_Outdoor_Air_Temperature",
  ],
  [
    "AHU-27-02.R.A._Temperature_1.Value",
    "isPointOf",
    "AHU_Return_Air_Temperature",
  ],
  ["AHU-27-02.S.A._Humidity.Value", "isPointOf", "AHU_Supply_Air_Humidity"],
  [
    "AHU-27-02.R.A._CO2_Concentration.Value",
    "isPointOf",
    "AHU_Return_Air_CO2_Concentration",
  ],
  [
    "AHU-27-02.Water_Supply_Temperature.Value",
    "isPointOf",
    "AHU_Water_Supply_Temperature",
  ],
  [
    "AHU-27-02.S.A._Temperature_Setpoint.Value",
    "isPointOf",
    "AHU_Supply_Air_Temperature_Setpoint",
  ],
  [
    "AHU-27-02.CO2_Concentration_Setpoint.Value",
    "isPointOf",
    "AHU_CO2_Concentration_Setpoint",
  ],
  ["FDD_AHU_CO2_Test", "isPartOf", "FDD_AHU"],
  ["FDD_AHU_S.A_SP_Temp_Test", "isPartOf", "FDD_AHU"],
  ["FDD_AHU_S.A_R.A_Temp_Test", "isPartOf", "FDD_AHU"],
  ["AHU", "hasFDD", "FDD_AHU"],
  ["Chiller_Contact_Sensor", "isPartOf", "Chiller"],
  ["Chiller_Supply_Chilled_Water_Temperature_Setpoint", "isPartOf", "Chiller"],
  ["Chiller_Return_Condenser_Water_Flow_Sensor", "isPartOf", "Chiller"],
  ["Chiller_On_Off_Status", "isPartOf", "Chiller"],
  ["Chiller_Temperature_Sensor", "isPartOf", "Chiller"],
  ["Chiller_Outside_Air_Temperature_Sensor", "isPartOf", "Chiller"],
  ["Chiller_Chilled_Water_Return_Temperature_Sensor", "isPartOf", "Chiller"],
  ["Chiller_Chilled_Water_Valve_On_Off_Control", "isPartOf", "Chiller"],
  ["Chiller_Chilled_Water_Supply_Temperature_Sensor", "isPartOf", "Chiller"],
  ["Chiller_CoP", "isPartOf", "Chiller"],
  ["Chiller_Outside_Air_Wet_Bulb_Temperature_Sensor", "isPartOf", "Chiller"],
  ["Chiller_Chilled_Water_Temperature_Reset", "isPartOf", "Chiller"],
  ["Chiller_Chilled_Water_Supply_Flow_Sensor", "isPartOf", "Chiller"],
  ["Chiller_CoP", "isPartOf", "Chiller"],
  ["Chiller_Cooling_Load", "isPartOf", "Chiller"],
  ["Chiller_Entering_Water_Temperature_Sensor", "isPartOf", "Chiller"],
  ["Chiller_Supply_Condenser_Water_Flow_Sensor", "isPartOf", "Chiller"],
  ["Chiller_Chilled_Water_Differential_Pressure_Sensor", "isPartOf", "Chiller"],
  ["Chiller_Return_Condenser_Water_Temperature_Sensor", "isPartOf", "Chiller"],
  ["Chilled_Chilled_Water_Pump_Delta_Temperature", "isPartOf", "Chiller"],
  [
    "Chiller_Supply_Condenser_Water_Temperature_Setpoint",
    "isPartOf",
    "Chiller",
  ],
  ["Chiller_Chilled_Water_Delta_Temperature", "isPartOf", "Chiller"],
  ["Chiller_Energy_Usage_Sensor", "isPartOf", "Chiller"],
  ["Chiller_Supply_Condenser_Water_Temperature_Sensor", "isPartOf", "Chiller"],
  ["Chiller_Cooling_Load", "subClassOf", "Virtual_Point"],
  ["CT_Approach_Temperature", "subClassOf", "Virtual_Point"],
  ["CT_Wet_Bulb", "subClassOf", "Virtual_Point"],
  [
    "Chilled_Chilled_Water_Pump_Delta_Temperature",
    "subClassOf",
    "Virtual_Point",
  ],
  ["Chiller_CoP", "subClassOf", "Virtual_Point"],
  ["AHU_Flow_Status", "isFDDPointOf", "FDD_AHU_S.A_SP_Temp_Test"],
  [
    "AHU_Supply_Air_Temperature_Setpoint",
    "isFDDPointOf",
    "FDD_AHU_S.A_SP_Temp_Test",
  ],
  ["AHU_Supply_Air_Temperature", "isFDDPointOf", "FDD_AHU_S.A_SP_Temp_Test"],
  ["B1F", "isLocationOf", "EnergySys_AHU"],
  ["B1F", "isLocationOf", "EnergySys_WCC"],
  ["WCC-25-03", "isPointOf", "Chiller"],
  ["25F", "isLocationOf", "WCC-25-03"],
  ["WCC-25-02", "isPointOf", "Chiller"],
  ["25F", "isLocationOf", "WCC-25-02"],
  ["WCC-25-01", "isPointOf", "Chiller"],
  ["25F", "isLocationOf", "WCC-25-01"],
  ["WCC-25-01.Chilled_Water_Temperature_Reset", "isPartOf", "WCC-25-01"],
  ["WCC-25-01.Chilled_Water_Return_Temperature.Value", "isPartOf", "WCC-25-01"],
  [
    "WCC-25-01.Condenser_Water_Differential_Pressure.Value",
    "isPartOf",
    "WCC-25-01",
  ],
  ["WCC-25-01.Condenser_Water_Valve_On_Off_Control", "isPartOf", "WCC-25-01"],
  [
    "WCC-25-01.Condenser_Water_Supply_Temperature.Value",
    "isPartOf",
    "WCC-25-01",
  ],
  ["WCC-25-01.Chilled_Water_Supply_Temperature.Value", "isPartOf", "WCC-25-01"],
  [
    "WCC-25-01.Chilled_Water_Differential_Pressure.Value",
    "isPartOf",
    "WCC-25-01",
  ],
  [
    "WCC-25-01.Condenser_Water_Return_Temperature.Value",
    "isPartOf",
    "WCC-25-01",
  ],
  ["WCC-25-01.Chilled_Water_Valve_On_Off_Control", "isPartOf", "WCC-25-01"],
];

module.exports = data;
